version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command:
      ["make", "dev"]
    volumes:
      - ./app:/app

  caddy:
    image: caddy:2.9.1-alpine
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
      - "443:443/udp"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    depends_on:
      - app