name: 'push action'

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Copy .env
        run: cp .env.example .env

      - name: Build image
        run: make build

      - name: Run tests
        run: make test

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.production
          tags: architecture2/devops-for-programmers-project-74:latest