name: push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Устанавливаем Docker и Docker Compose
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # Запускаем тесты
      - run: make test